//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeSamples.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class OtherSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static OtherSettings defaultInstance = ((OtherSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OtherSettings())));
        
        public static OtherSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SomeOtherStringSetting {
            get {
                return ((string)(this["SomeOtherStringSetting"]));
            }
            set {
                this["SomeOtherStringSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SomeOtherIntSetting {
            get {
                return ((int)(this["SomeOtherIntSetting"]));
            }
            set {
                this["SomeOtherIntSetting"] = value;
            }
        }
    }
}
